import { Colors } from "@/core/theme/colors";
import { Fonts } from "@/core/theme/fonts";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  mainContainer: { flex: 1, backgroundColor: "#fff" },
  header: { backgroundColor: "#fff", borderBottomWidth: 0.5, borderBottomColor: "#EAEAEF", paddingBottom: 10 },
  headerMain: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingHorizontal: 16, paddingTop: 12, paddingBottom: 10 },
  headerTitle: { fontSize: 24, fontFamily: Fonts.bold, color: Colors.light.text },
  headerActions: { flexDirection: "row", alignItems: "center" },
  headerButton: { padding: 8, marginLeft: 8, borderRadius: 20, backgroundColor: "#F2F2F7" },
  tabsContainer: { maxHeight: 44 },
  tabsContent: { paddingHorizontal: 16, alignItems: "center", gap: 8, paddingRight: 32 },
  tabCapsule: { flexDirection: "row", alignItems: "center", paddingHorizontal: 14, paddingVertical: 7, borderRadius: 18, backgroundColor: "#F2F2F7", borderWidth: 1, borderColor: "transparent" },
  tabCapsuleActive: { backgroundColor: Colors.light.primary, borderColor: Colors.light.primary },
  tabText: { fontSize: 13, fontFamily: Fonts.medium, color: "#636366" },
  tabTextActive: { color: "#FFFFFF", fontFamily: Fonts.bold },
  listContent: { paddingVertical: 4, flexGrow: 1 },
  activityCard: { flexDirection: "row", alignItems: "center", paddingVertical: 12, paddingHorizontal: 16, borderBottomWidth: 0.5, borderBottomColor: "#F2F2F7" },
  unreadCardBg: { backgroundColor: "#EEF2FF" },
  unreadIndicatorWrapper: { width: 10, justifyContent: "center", alignItems: "flex-start" },
  unreadDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: Colors.light.primary },
  avatarWrapper: { position: "relative", marginRight: 4 },
  avatar: { width: 44, height: 44, borderRadius: 22, backgroundColor: "#EAEAEF" },
  badgeContainer: { position: "absolute", bottom: -2, right: -2, width: 18, height: 18, borderRadius: 9, justifyContent: "center", alignItems: "center", borderWidth: 1.5, borderColor: "#FFFFFF" },
  textContainer: { flex: 1, paddingHorizontal: 10 },
  activityText: { fontSize: 13.5, fontFamily: Fonts.regular, color: Colors.light.text, lineHeight: 18 },
  username: { fontFamily: Fonts.semiBold },
  timeText: { color: "#8e8e93", fontSize: 12, fontFamily: Fonts.regular, marginLeft: 4 },
  commentPreviewBubble: { backgroundColor: "#F2F2F7", paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, marginTop: 4, alignSelf: "flex-start", maxWidth: "100%" },
  commentPreviewText: { fontSize: 12, fontFamily: Fonts.regular, color: "#636366", fontStyle: "italic" },
  rightAction: { justifyContent: "center", alignItems: "flex-end", minWidth: 70 },
  followButton: { backgroundColor: Colors.light.primary, paddingVertical: 6, paddingHorizontal: 10, borderRadius: 6, width: "100%", alignItems: "center", },
  followingActiveButton: { backgroundColor: "#F2F2F7" },
  followButtonText: { color: "#FFF", fontSize: 12, fontFamily: Fonts.semiBold },
  followingActiveText: { color: Colors.light.text },
  thumbnailWrapper: { position: "relative" },
  postThumbnail: { width: 44, height: 44, borderRadius: 8, backgroundColor: "#EAEAEF" },
  searchOverlay: { position: "absolute", bottom: 2, right: 2, backgroundColor: "rgba(0,0,0,0.5)", borderRadius: 10, padding: 2 },
  emptyContainer: { flex: 1, justifyContent: "center", alignItems: "center", paddingTop: 100, paddingHorizontal: 32 },
  emptyIconCircle: { width: 80, height: 80, borderRadius: 40, backgroundColor: "#F2F2F7", justifyContent: "center", alignItems: "center", marginBottom: 16 },
  emptyTitle: { fontSize: 18, fontFamily: Fonts.bold, color: Colors.light.text, marginBottom: 8 },
  emptyText: { fontSize: 14, fontFamily: Fonts.regular, color: "#8e8e93", textAlign: "center", lineHeight: 20 }
});